[package]
name    = "carnixhello"
version = "0.1.0"
authors = ["Benjamin Summers <benjamin@tlon.io>"]
# build   = "build.rs"

[lib]
name       = "carnixhello"
crate-type = ["staticlib"]

[dependencies]
regex = "0.1.41"
