#!/usr/bin/env bash

if [ -z "$CACHIX_AUTH_TOKEN" ]
then echo 'CACHIX_AUTH_TOKEN must be set.' 1>&2
     exit 1
fi

if [ -z "$CI" ] || [ -z "$TRAVIS" ]
then echo "Don't run this outside of CI. It will blow our cache"
     exit 1
fi

cachix authtoken "$CACHIX_AUTH_TOKEN" >/dev/null
cachix use urbit
nix-build | cachix push urbit
nix-build nix/git-cache.nix | cachix push urbit
nix-shell --pure --command ./sh/vere-tests
