#!/usr/bin/env bash

# Given an urbit executable and a pill, create a zod pier.

set -ex

test -n "$BOOTPILL"
test -n "$FAKEZOD"

mkdir -p "$(dirname "$FAKEZOD")"

rm -rf "$FAKEZOD"

urbit-runner -F zod -B "$BOOTPILL" "$FAKEZOD" </dev/null
