#!/usr/bin/env bash

set -e

err () { echo "$@" >&2; exit 1; }

[ $# = 2 ] || err "usage: $0 pkg host"

traced () {
  echo '$' "$@" >&2; "$@"
}

release () {
  traced nix-build nix/release.nix --no-out-link -A "$1"
}

pkg="$1"
env="$2"

res=$(release "$pkg-$env")

mkdir -p ./release/$env/bin/
traced cp -f $res/bin/* ./release/$env/bin/
