#!/usr/bin/env bash

set -ex

test -n "$ARVO"
test -n "$FAKEZOD"
test -n "$PILL"

test -d "$ARVO"
test -d "$FAKEZOD"
test ! -e "$PILL"

urbit-runner -S "$FAKEZOD" <<EOF
|autoload |
|mount %
EOF

cp -r $ARVO/sys            $FAKEZOD/home/
cp    $ARVO/gen/solid.hoon $FAKEZOD/home/gen/
cp    $ARVO/lib/pill.hoon  $FAKEZOD/home/lib/

urbit-runner -S $FAKEZOD <<EOF
.urbit/pill +solid, =dub &
EOF

mkdir -p "$(dirname $PILL)"

cp "$FAKEZOD/.urb/put/urbit.pill" "$PILL"
