[package]
name    = "rusthello"
version = "0.1.0"
authors = ["Benjamin Summers <benjamin@tlon.io>"]
build   = "build.rs"

[lib]
name       = "rusthello"
crate-type = ["staticlib"]

[dependencies]
regex = "0.1.41"
