# use trusty beta (ubuntu 14.04)
sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install --yes cmake

script:
  - cmake .
  - make all
  - make check
